let myData  = [
    {
      "day":1,
      "data":[
            {
              "name":"pis",
              "weight":30
            },
            {
              "name":"pir",
              "weight":30
            }
        ]
    },
        {
      "day":2,
      "data":[
            {
              "name":"pis",
              "weight":31
            },
            {
              "name":"pir",
              "weight":32
            }
        ]
    },
    {
      "day":3,
      "data":[
          {
            "name":"pis",
            "weight":30
          },
          {
            "name":"pir",
            "weight":30
          }
      ]
  },
    {
    "day":4,
    "data":[
          {
            "name":"pis",
            "weight":31
          },
          {
            "name":"pir",
            "weight":32
          }
      ]
  }
]

export {myData};